services:
  # Serviço principal Python/Streamlit
  rag-app:
    build:
      context: ./GENAI-RAG-generalist
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - KEYCLOAK_URL=http://localhost:8080
      - KEYCLOAK_URL_INTERNO=http://keycloak:8080
      - KEYCLOAK_REALM=neuai
      - KEYCLOAK_CLIENT_ID=genai
      - KEYCLOAK_REDIRECT_URI=http://localhost:8501/
      # Adicione variáveis de ambiente necessárias aqui
    depends_on:
      - api
      - keycloak
    networks:
      - keycloak_network

  # API .NET
  api:
    build:
      context: ./GENAI-RAG-generalist.API
      dockerfile: Dockerfile
    ports:
      - "5254:80"
      - "7186:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword123!
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=dddtemplate;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
    volumes:
      - ./GENAI-RAG-generalist.API/certificates:/https:ro
    depends_on:
      - postgres
      - redis
    networks:
      - keycloak_network

  # Banco de dados da API
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dddtemplate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  # Redis para a API
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - keycloak_network

  # Keycloak Auth
  keycloak:
    build:
      context: ./GENAI-RAG-generalist.auth
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KC_DB_URL=jdbc:postgresql://keycloak-db/keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_PASSWORD=keycloakpwd
      - KC_DB_USERNAME=keycloakusr
      - KC_DB=postgres
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME=localhost #IPv4 da rede do WI-FI
      - KC_PROXY=edge
      - KC_FRONTEND_URL=http://localhost:8080 #IPv
    volumes:
      - ./GENAI-RAG-generalist.auth/template-theme:/opt/keycloak/themes/template
      - ./GENAI-RAG-generalist.auth/realm-import-dev-env:/opt/keycloak/data/import
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --import-realm
      - --features=preview
    depends_on:
      - keycloak-db
    networks:
      - keycloak_network

  # Banco de dados do Keycloak
  keycloak-db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloakusr
      - POSTGRES_PASSWORD=keycloakpwd
    ports:
      - "5433:5432"
    networks:
      - keycloak_network

volumes:
  postgres-data:
  redis-data:

networks:
  keycloak_network:
    driver: bridge