version: '3'
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KC_DB_URL=jdbc:postgresql://db/keycloak
      - KC_DB_PASSWORD=keycloakpwd
      - KC_DB_USERNAME=keycloakusr
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME=localhost #IPv4 da rede do WI-FI
      - KC_PROXY=edge
      - KC_FRONTEND_URL=http://localhost:8080 #IPv4 da rede do WI-FI
    volumes:
      - ./template-theme:/opt/keycloak/themes/template
      - ./realm-import-dev-env:/opt/keycloak/data/import
    command:
      - start-dev
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --import-realm
      - --features=preview
    networks:
      - keycloak_network

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloakusr
      POSTGRES_PASSWORD: keycloakpwd
    ports:
      - "5432:5432"
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

# exeute o comando para escolher o arquivo:
# docker compose -f docker-compose.local.yml up -d

# executo no cmd como administrador:
# 172.27.64.1 é IPv4 do WSL
# 192.168.0.5 é IPv4 do rede WI-FI
# execute o comando "ipconfig" para pegar os ips
# [OPTIONAL]netsh interface portproxy add v4tov4 listenport=8080 listenaddress=192.168.0.5 connectport=8080 connectaddress=172.27.64.1
# netsh interface portproxy show all
# [OPTIONAL]execute o comando para liberar as portas no firewall "netsh advfirewall firewall add rule name="WSL Keycloak" dir=in action=allow protocol=TCP localport=8080"

#apos utilizar retorna a configuração inicial:

# ative o ferewal "netsh advfirewall set allprofiles state on"
# [OPTIONAL]netsh interface portproxy delete v4tov4 listenport=8080 listenaddress=192.168.0.5
# [OPTIONAL]netsh advfirewall firewall delete rule name="WSL Keycloak"
